export const FIFA_TO_ISO: Record<string, string> = {
  ALG: "dz",
  ARG: "ar",
  AUS: "au",
  AUT: "at",
  BEL: "be",
  BIH: "ba",
  BRA: "br",
  CAN: "ca",
  CHI: "cl",
  CIV: "ci",
  CMR: "cm",
  COD: "cd",
  COL: "co",
  CPV: "cv",
  CRC: "cr",
  CRO: "hr",
  CUW: "cw",
  CZE: "cz",
  DEN: "dk",
  ECU: "ec",
  EGY: "eg",
  ENG: "gb",
  ESP: "es",
  FRA: "fr",
  GER: "de",
  GHA: "gh",
  GRE: "gr",
  HAI: "ht",
  HON: "hn",
  ISL: "is",
  IRN: "ir",
  IRQ: "iq",
  ITA: "it",
  JOR: "jo",
  JPN: "jp",
  KOR: "kr",
  KSA: "sa",
  MAR: "ma",
  MEX: "mx",
  NED: "nl",
  NGA: "ng",
  NOR: "no",
  NZL: "nz",
  PAN: "pa",
  PAR: "py",
  PER: "pe",
  POL: "pl",
  POR: "pt",
  QAT: "qa",
  RSA: "za",
  RUS: "ru",
  SCO: "gb-sct",
  SEN: "sn",
  SRB: "rs",
  SUI: "ch",
  SWE: "se",
  TUN: "tn",
  TUR: "tr",
  URU: "uy",
  USA: "us",
  UZB: "uz",
  WAL: "gb-wls",
};

export function getFlagUrl(fifaCode: string): string {
  const iso = FIFA_TO_ISO[fifaCode.toUpperCase()];
  if (!iso) return "";
  return `https://flagcdn.com/${iso}.svg`;
}
